# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('channel_type', models.CharField(choices=[(b'image', b'IMAGES'), (b'annotation', b'ANNOTATIONS'), (b'timeseries', b'TIMESERIES')], max_length=255)),
                ('resolution', models.IntegerField(default=0)),
                ('propagate', models.IntegerField(choices=[(0, b'NOT PROPAGATED'), (2, b'PROPAGATED')], default=0)),
                ('channel_datatype', models.CharField(choices=[(b'uint8', b'uint8'), (b'uint16', b'uint16'), (b'uint32', b'uint32'), (b'uint64', b'uint64'), (b'float32', b'float32')], max_length=255)),
                ('readonly', models.IntegerField(choices=[(1, b'Yes'), (0, b'No')], default=0)),
                ('startwindow', models.IntegerField(default=0)),
                ('endwindow', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_name', models.CharField(max_length=255, unique=True)),
                ('dataset_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ximagesize', models.IntegerField()),
                ('yimagesize', models.IntegerField()),
                ('zimagesize', models.IntegerField()),
                ('xoffset', models.IntegerField(default=0.0)),
                ('yoffset', models.IntegerField(default=0.0)),
                ('zoffset', models.IntegerField(default=0.0)),
                ('xvoxelres', models.FloatField(default=1.0)),
                ('yvoxelres', models.FloatField(default=1.0)),
                ('zvoxelres', models.FloatField(default=1.0)),
                ('scalingoption', models.IntegerField(choices=[(0, b'Z Slices'), (1, b'Isotropic')], default=0)),
                ('scalinglevels', models.IntegerField(default=0)),
                ('starttime', models.IntegerField(default=0)),
                ('endtime', models.IntegerField(default=0)),
                ('project_name', models.CharField(max_length=255)),
                ('s3backend', models.IntegerField(choices=[(1, b'Yes'), (0, b'No')], default=1)),
            ],
            options={
                'db_table': 'datasets',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='channels',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilecache.Dataset'),
        ),
    ]
