# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilecache', '0002_auto_20160317_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='channel',
            table='channels',
        ),
    ]
