# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilecache', '0003_auto_20160317_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set([('channel_name', 'dataset_id')]),
        ),
    ]
