# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilecache', '0004_auto_20160317_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='dataset_id',
            new_name='dataset',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set([('channel_name', 'dataset')]),
        ),
    ]
